name: nuxt
description: A starter project showing how to make use of JSX with Typescript in Nuxt.js
keywords:
  - nuxt.js
  - typescript
  - jsx
  - tsx

secrets:
  APP_NAME:
    description: Name of the application to use in page metadata
    default: Nuxt TSX Starter

services:
  app:
    build:
      context: ./
      ${{ if architect.environment == 'local' }}:
        args:
          DEBUG: 'true'
    environment:
      BASE_URL: ${{ ingresses.app.url }}
      APP_NAME: ${{ secrets.APP_NAME }}
    interfaces:
      main: 3000
    ${{ if architect.environment == 'local' }}:
      command: npm run dev
      volumes:
        src:
          host_path: ./src/
          mount_path: /app/src/

interfaces:
  app:
    url: ${{ services.app.interfaces.main.url }}
    description: Exposes the webapp to outside consumers
    ingress:
      subdomain: app
