name: nuxt
description: A starter project showing how to make use of Typescript in Nuxt.js
keywords:
  - nuxt.js
  - typescript
  - vue

dependencies:
  node-rest-api: latest

secrets:
  APP_NAME:
    description: Name of the application to use in page metadata
    default: Nuxt Starter

services:
  app:
    command: npm run start
    build:
      context: ./
      args:
        NODE_ENV: production
    environment:
      APP_NAME: ${{ secrets.APP_NAME }}
      APP_API_ADDR: ${{ dependencies['node-rest-api'].services.api.interfaces.main.url }}
    interfaces:
      main:
        port: 3000
        ingress:
          subdomain: app
    liveness_probe:
      command: curl --fail localhost:3000
      initial_delay: 120s
      interval: 30s
      failure_threshold: 3
    debug:
      command: npm run dev
      build:
        args:
          NODE_ENV: development
      volumes:
        src:
          host_path: ./src/
          mount_path: /app/src/
