name: nuxt
description: A starter project showing how to make use of JSX with Typescript in Nuxt.js
keywords:
  - nuxt.js
  - typescript
  - jsx
  - tsx

dependencies:
  node-rest-api: latest

secrets:
  APP_NAME:
    description: Name of the application to use in page metadata
    default: Nuxt TSX Starter

services:
  app:
    build:
      context: ./
      args:
        NODE_ENV: production
    environment:
      BASE_URL: ${{ ingresses.app.url }}
      APP_NAME: ${{ secrets.APP_NAME }}
      APP_API_ADDR: ${{ dependencies['node-rest-api'].ingresses.api.url }}
    interfaces:
      main: 3000
    liveness_probe:
      command: curl --fail localhost:3000
      interval: 30s
      failure_threshold: 3
    debug:
      command: npm run dev
      build:
        args:
          NODE_ENV: development
      volumes:
        src:
          host_path: ./src/
          mount_path: /app/src/

interfaces:
  app:
    url: ${{ services.app.interfaces.main.url }}
    description: Exposes the webapp to outside consumers
    ingress:
      subdomain: app
