name: nuxt
description: A starter project showing how to make use of JSX with Typescript in Nuxt.js
keywords:
  - nuxt.js
  - typescript
  - jsx
  - tsx

secrets:
  APP_NAME:
    description: Name of the application to use in page metadata
    default: Nuxt TSX Starter

services:
  app:
    build:
      context: ./
      args:
        NODE_ENV: production
    environment:
      BASE_URL: ${{ services.app.interfaces.main.ingress.url }}
      APP_NAME: ${{ secrets.APP_NAME }}
    interfaces:
      main:
        port: 3000
        ingress:
          subdomain: app
    liveness_probe:
      command: curl --fail localhost:3000
      interval: 30s
      failure_threshold: 3
    debug:
      command: npm run dev
      build:
        args:
          NODE_ENV: development
      volumes:
        src:
          host_path: ./src/
          mount_path: /app/src/
